export const ErrorCode = {
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_NOT_ACTIVE: 'WALLET_NOT_ACTIVE',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  UNSUPPORTED_CURRENCY: 'UNSUPPORTED_CURRENCY',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  SAME_WALLET_TRANSFER: 'SAME_WALLET_TRANSFER',
  SYSTEM_WALLET_NOT_ALLOWED: 'SYSTEM_WALLET_NOT_ALLOWED',
  CONCURRENCY_CONFLICT: 'CONCURRENCY_CONFLICT',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  IDEMPOTENCY_PAYLOAD_MISMATCH: 'IDEMPOTENCY_PAYLOAD_MISMATCH',
  SERIALIZATION_FAILURE: 'SERIALIZATION_FAILURE',
  RECONCILIATION_DRIFT_DETECTED: 'RECONCILIATION_DRIFT_DETECTED',
  WALLET_RISK_BLOCKED: 'WALLET_RISK_BLOCKED',
  CIRCUIT_BREAKER_OPEN: 'CIRCUIT_BREAKER_OPEN',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
