export const AnomalyFlag = {
  HIGH_DEPOSIT_RATE: 'HIGH_DEPOSIT_RATE',
  HIGH_WITHDRAW_RATE: 'HIGH_WITHDRAW_RATE',
  HIGH_TRANSFER_RATE: 'HIGH_TRANSFER_RATE',
  UNUSUAL_AMOUNT: 'UNUSUAL_AMOUNT',
  ROUND_AMOUNT_PATTERN: 'ROUND_AMOUNT_PATTERN',
  UNUSUAL_TRANSFER_CYCLE: 'UNUSUAL_TRANSFER_CYCLE',
  SELF_TRANSFER_LOOP: 'SELF_TRANSFER_LOOP',
  FEE_WALLET_INFLOW_SPIKE: 'FEE_WALLET_INFLOW_SPIKE',
} as const;

export type AnomalyFlagCode = (typeof AnomalyFlag)[keyof typeof AnomalyFlag];
